### ISSUE TITLE
Getting error, submitting code with Javascript, on using SPJ. Works fine for other languages.

### ISSUE THREAD

**Issue by rrutwik** [QingdaoU/Judger#49]
2020-12-29 03:27:05,567 ERROR Expecting value: line 1 column 1 (char 0)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/code/judge_client.py", line 20, in _run
    return instance._judge_one(test_case_file_id)
  File "/code/judge_client.py", line 155, in _judge_one
    spj_result = self._spj(in_file_path=in_file, user_out_file_path=user_output_file)
  File "/code/judge_client.py", line 91, in _spj
    gid=SPJ_GROUP_GID)
  File "/usr/local/lib/python3.6/dist-packages/_judger/__init__.py", line 84, in run
    return json.loads(out.decode("utf-8"))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/server.py", line 192, in server
    ret = {"err": None, "data": getattr(JudgeServer, path)(**data)}
  File "/code/server.py", line 150, in judge
    run_result = judge_client.run()
  File "/code/judge_client.py", line 209, in run
    result.append(item.get())
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by virusdefender** [comment]
Python 这边和 Judger 进程是通过 stdout 的 json 通信的，所以 json 不对就会异常，你可以看下 `/usr/local/lib/python3.6/dist-packages/_judger/init.py` 把 stdout 打印出来看下，或者手动运行 judger 进程看看会输出啥。

**Comment by rrutwik** [comment]
It was due to this error  "integer overflow at option --max_memory=<n> (3145728000 is too large) Try 'libjudger.so --help' for more information."
